# Generated by Django 5.2.8 on 2025-11-13 13:21

import dedicatory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dedicatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teu', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('mae', 'Mother'), ('namorado', 'GirlFriend/BoyFriend'), ('irmao', 'Brother/Sister')], max_length=20)),
                ('contexto', models.CharField(choices=[('amor', 'Loving'), ('carinho', 'Cart'), ('amizade', 'Friendship')], max_length=20)),
                ('codigo', models.CharField(default=dedicatory.models.gerar_codigo_unico, max_length=20, unique=True)),
                ('photo1', models.FileField(blank=True, upload_to='dedicatorias/')),
                ('photo2', models.FileField(blank=True, null=True, upload_to='dedicatorias/')),
                ('photo3', models.FileField(blank=True, null=True, upload_to='dedicatorias/')),
                ('photo4', models.FileField(blank=True, null=True, upload_to='dedicatorias/')),
                ('photo5', models.FileField(blank=True, null=True, upload_to='dedicatorias/')),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
