# Generated by Django 5.2.8 on 2025-11-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedicatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatory',
            name='tipo',
            field=models.CharField(choices=[('mae', 'Mother'), ('namorado', 'GirlFriend/BoyFriend'), ('irmao', 'Brother/Sister'), ('amigo', 'Friend')], max_length=20),
        ),
    ]
