# Generated by Django 5.2.8 on 2025-11-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedicatory', '0002_alter_dedicatory_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedicatory',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='dedicatorias/'),
        ),
        migrations.AlterField(
            model_name='dedicatory',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='dedicatorias/'),
        ),
        migrations.AlterField(
            model_name='dedicatory',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='dedicatorias/'),
        ),
        migrations.AlterField(
            model_name='dedicatory',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='dedicatorias/'),
        ),
        migrations.AlterField(
            model_name='dedicatory',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='dedicatorias/'),
        ),
        migrations.AlterField(
            model_name='dedicatory',
            name='tipo',
            field=models.CharField(choices=[('mae', 'Mother'), ('pai', 'Father'), ('namorado', 'GirlFriend/BoyFriend'), ('irmao', 'Brother/Sister'), ('amigo', 'Friend')], max_length=20),
        ),
    ]
